In [ ]:
from IPython.core.display import display, HTML
display(HTML("<style>.container {width:90% !important;}</style>"))

In [5]:
from rpy2 import robjects
import pandas as pd

In [25]:
from rpy2.robjects.packages import importr, data

datasets = importr('AppliedPredictiveModeling')
R_data = data(datasets).fetch('segmentationOriginal')['segmentationOriginal']
R_data

<rpy2.robjects.vectors.DataFrame object at 0x7fdaf87cd690> [RTYPES.VECSXP]
R classes: ('data.frame',)
[IntSexpVe..., IntSexpVe..., IntSexpVe..., FloatSexp..., ..., FloatSexp..., IntSexpVe..., IntSexpVe..., IntSexpVe...]
  Cell: <class 'rpy2.robjects.vectors.IntVector'>
  <rpy2.robjects.vectors.IntVector object at 0x7fdaf87cd730> [RTYPES.INTSXP]
R classes: ('integer',)
[207827637, 207932307, 207932463, 207932470, ..., 210952142, 210952338, 210948231, 210948238]
  Case: <class 'rpy2.robjects.vectors.FactorVector'>
  <rpy2.robjects.vectors.FactorVector object at 0x7fdaf87cd640> [RTYPES.INTSXP]
R classes: ('factor',)
[Test, Train, Train, Train, ..., Test, Test, Test, Train]
  Class: <class 'rpy2.robjects.vectors.FactorVector'>
  <rpy2.robjects.vectors.FactorVector object at 0x7fdaf87cd410> [RTYPES.INTSXP]
R classes: ('factor',)
[PS, PS, WS, PS, ..., PS, PS, WS, WS]
  AngleCh1: <class 'rpy2.robjects.vectors.FloatVector'>
  <rpy2.robjects.vectors.FloatVector object at 0x7fdaf87cd370> [RTYPES.REALSXP]
R classes: ('numeric',)
[143.247705, 133.752037, 106.646387, 69.150325, ..., 99.049010, 83.319801, 116.473894, 150.820416]
...
  AreaCh1: <class 'rpy2.robjects.vectors.FloatVector'>
  <rpy2.robjects.vectors.FloatVector object at 0x7fdaf87cd050> [RTYPES.REALSXP]
R classes: ('numeric',)
[10.642974, 32.161261, 21.185525, 13.392830, ..., 24.524072, 9.985410, 22.440286, 21.789495]
  AreaStatusCh1: <class 'rpy2.robjects.vectors.IntVector'>
  <rpy2.robjects.vectors.IntVector object at 0x7fdaf87ccfa0> [RTYPES.INTSXP]
R classes: ('integer',)
[2, 1, 0, 0, ..., 1, 2, 1, 0]
  AvgIntenCh1: <class 'rpy2.robjects.vectors.IntVector'>
  <rpy2.robjects.vectors.IntVector object at 0x7fdaf87ccd70> [RTYPES.INTSXP]
R classes: ('integer',)
[42, 215, 371, 487, ..., 313, 291, 100, 71]
  AvgIntenCh2: <class 'rpy2.robjects.vectors.IntVector'>
  <rpy2.robjects.vectors.IntVector object at 0x7fdaf87cca50> [RTYPES.INTSXP]
R classes: ('integer',)
[14, 347, 252, 295, ..., 88, 402, 448, 480]

In [26]:
df1 = pd.DataFrame(R_data).T
df1.columns = list(R_data.colnames)

In [27]:
df1

,Cell,Case,Class,AngleCh1,AngleStatusCh1,AreaCh1,AreaStatusCh1,AvgIntenCh1,AvgIntenCh2,AvgIntenCh3,...,VarIntenCh1,VarIntenCh3,VarIntenCh4,VarIntenStatusCh1,VarIntenStatusCh3,VarIntenStatusCh4,WidthCh1,WidthStatusCh1,XCentroid,YCentroid
0,207827637.0,1.0,1.0,143.247705,1.0,185.0,0.0,15.711864,3.954802,9.548023,...,12.474676,7.609035,2.714100,0.0,2.0,2.0,10.642974,2.0,42.0,14.0
1,207932307.0,2.0,1.0,133.752037,0.0,819.0,1.0,31.923274,205.878517,69.916880,...,18.809225,56.715352,118.388139,0.0,0.0,0.0,32.161261,1.0,215.0,347.0
2,207932463.0,2.0,2.0,106.646387,0.0,431.0,0.0,28.038835,115.315534,63.941748,...,17.295643,37.671053,49.470524,0.0,0.0,0.0,21.185525,0.0,371.0,252.0
3,207932470.0,2.0,1.0,69.150325,0.0,298.0,0.0,19.456140,101.294737,28.217544,...,13.818968,30.005643,24.749537,0.0,0.0,2.0,13.392830,0.0,487.0,295.0
4,207932455.0,1.0,1.0,2.887837,2.0,285.0,0.0,24.275735,111.415441,20.474265,...,15.407972,20.504288,45.450457,0.0,0.0,0.0,13.198561,0.0,283.0,159.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014,210948219.0,2.0,1.0,85.481047,0.0,302.0,0.0,42.041522,23.467128,143.532872,...,26.648000,102.644041,138.501314,0.0,0.0,0.0,24.979033,1.0,208.0,379.0
2015,210952142.0,1.0,1.0,99.049010,0.0,607.0,0.0,38.803448,20.587931,78.372414,...,28.429877,76.190478,119.199303,0.0,0.0,0.0,24.524072,1.0,313.0,88.0
2016,210952338.0,1.0,1.0,83.319801,0.0,204.0,0.0,37.866667,5.994872,59.789744,...,24.139396,37.024343,63.198797,0.0,2.0,2.0,9.985410,2.0,291.0,402.0
2017,210948231.0,1.0,2.0,116.473894,0.0,390.0,0.0,45.643432,169.123324,147.498660,...,37.641158,154.151167,330.195989,0.0,0.0,0.0,22.440286,1.0,100.0,448.0
2018,210948238.0,2.0,2.0,150.820416,1.0,441.0,0.0,35.641330,118.372922,96.738717,...,26.664576,96.042588,174.632667,0.0,0.0,0.0,21.789495,0.0,71.0,480.0